### PR TITLE
Fix sensor behavior

### PR DESCRIPTION
**Pull request by doudou**
Depends on:
- [ ] https://github.com/rock-gazebo/simulation-orogen-rock_gazebo/pull/23

In conjunction with the changes in the orogen project, this fixes random failures while running
tests, that were due to the bad integration of gazebo-to-port communication.

### CODE REVIEW

**Review by gabrielfpacheco — COMMENTED** [review]
Nice work! I have successfully tested it by running the a complete system simulation.
 
However, I am having issues when running the tests, for some reason it appears that the `helpers.rb` dependency is not being loaded. I tried, unsuccessfully, running the tests both manually and by doing the following:

```console
acd - b .
ctest -V
```
Since I am relatively new to testing OroGen components, it is likely that I am missing something on my end, could you detail the test procedure so that I can run the tests properly? I appreciate the support.

**Comment by doudou** [comment]
Could you try to figure it out from this documentation : it will give some feedback on its "understandability"

https://www.rock-robotics.org/rock-and-syskit/workspace/testing.html

**Review by gabrielfpacheco — COMMENTED** [review]
> Could you try to figure it out from this documentation : it will give some feedback on its "understandability"
> 
> https://www.rock-robotics.org/rock-and-syskit/workspace/testing.html

Thanks, Sylvain! Now I think everything is configured correctly. But I was only able to run the tests after the I performed the suggested changes.

**Comment by doudou** [comment]
Thanks @gabrielfpacheco. CI actually failed on it, but I failed to see it because there was so many builds this last day :(

Need to improve on our dashboard...

**Comment by doudou** [comment]
And it does not even pass. Fixing it, I'll re-request a review afterwards.

Sorry for the noise.

**Comment by doudou** [comment]
@gabrielfpacheco should pass now

**Review by g-arjones — APPROVED** [review]

**Review by gabrielfpacheco — APPROVED** [review]
All good now! :)

**Pull request merged**
